### PR TITLE
remove -AmergeStubsWithSource, because it's not needed with Ajava files

### PR DESCRIPTION
**Pull request by kelloggm**
~Merge after https://github.com/typetools/checker-framework/pull/4753~

@jwaataja, I can't add you as a reviewer because you don't have permissions on this repo. I've sent you an invite link, and I'd love a review from you on this PR. Thanks!

### CODE REVIEW

**Comment by jwaataja** [comment]
Not sure why the CI is failing. Can't reproduce the failure if I run the tests locally.

**Comment by kelloggm** [comment]
I'll look into it.

**Comment by kelloggm** [comment]
I've been able to reproduce this issue locally using these steps:
```
cd /tmp/
git clone git@github.com:kelloggm/do-like-javac.git
cd do-like-javac
git checkout no-amergestubswithsource
export DLJC=./dljc
cd ..
git clone git@github.typetools/checker-framework.git
cd checker-framework
./gradlew :checker:wpiPlumeLibTests
```

I've found the use of `-AmergeStubsWithSource` in the CF implementation that's responsible for these failures (that is, the use that the current version is dependent on). It's in AnnotationFileParser here: https://github.com/typetools/checker-framework/blob/e50e728000d478c5249a56d280db8a40a3addc40/framework/src/main/java/org/checkerframework/framework/stub/AnnotationFileParser.java#L732. In particular, it seems that some relevant nodes are being skipped when parsing ajava files without `-AmergeStubsWithSource`. I determined this by modifying the CF to remove that reference to `-AmergeStubsWithSource` - that is, by making it skip nodes in stub files regardless of the option - and re-running the relevant test with the option supplied. I got the same output that shows up in CI for this PR when I did that.

This seems to violate the contract of ajava files, which should always be fully parsed. I suspect that the problem has something to do with the `AJAVA_AS_STUB` option in `AnnotationFileType`, which seems suspicious to me - I don't see any other way that the `isStubFile()` test should pass when parsing an ajava file (and is `isStubFile()` is false, then the `-AmergeStubsWithSource` option is definitely ignored. I'm not familiar with the purpose of that option, so maybe @jwaataja you have an idea of what might be going on here?

**Comment by jwaataja** [comment]
@kelloggm Any ajava file is also a valid stub file. We wanted to reuse most of the stub file code where possible. So, for a class C, an ajava file for C would be processed twice. It's a processed once a stub file, which has sufficient type information when type checking classes other than C. When processing C itself, the file is processed again and annotations in method bodies and other locations are read in.

This is why `AnnotationFileType` has `AJAVA_AS_STUB`, which I believe is used during that first phase. If it's set, then `isStub` returns `true`. During this phase, we want the ajava file to be processed as a stub file as if `-AmergeStubsWithSource` were on, even the option is not passed. The fix might be to replace the test with `isStubFile() && fileType != AnnotationFileType.AJAVA_AS_STUB && !mergeStubsWithSource`. A similar check is used on line 622 of `AnnotationFileParser`.

**Comment by kelloggm** [comment]
@jwaataja that makes sense. The change you suggested seems to have fixed the problem for me locally.

**Pull request merged**
